export const GESTION_PERMISSIONS = {
  SETTINGS: 18,
  PAYMENT_TYPES: 19,
  EMPLOYEES_CREATE: 20,
  EMPLOYEES_UPDATE: 21,
  EMPLOYEES_DELETE: 22,
  EMPLOYEES_PERMISSIONS: 23,
  EMPLOYEES_STATISTICS: 24,
  BACKUPS: 25,
} as const;

export const GESTION_EMPLOYEES_PERMISSIONS: readonly number[] = [
  GESTION_PERMISSIONS.EMPLOYEES_CREATE,
  GESTION_PERMISSIONS.EMPLOYEES_UPDATE,
  GESTION_PERMISSIONS.EMPLOYEES_DELETE,
  GESTION_PERMISSIONS.EMPLOYEES_PERMISSIONS,
  GESTION_PERMISSIONS.EMPLOYEES_STATISTICS,
];
